name: Laravel CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install deps
        run: composer install --working-dir=quoodle-control-plane --no-interaction
      - name: Lint
        run: cd quoodle-control-plane && ./vendor/bin/pint --test || true
      - name: Tests
        run: cd quoodle-control-plane && php artisan test --testsuite=Feature
